# https://mlflow.org

mlflow:
  _target_: lightning.pytorch.loggers.mlflow.MLFlowLogger
  # experiment_name: ""
  # run_name: ""
  #tracking_uri: ${paths.log_dir}/mlflow/mlruns # run `mlflow ui` command inside the `logs/mlflow/` dir to open the UI
  tracking_uri: ${oc.env:MLFLOW_TRACKING_URI}
  tags: null
  # save_dir: "./mlruns"
  prefix: ""
  artifact_location: null
  # run_id: ""
